### ISSUE TITLE
[MGTrapdoorSpleef] Task #564337 for MGTrapdoorSpleef v1.2.0 generated an exception

### ISSUE THREAD

**Issue by XxCoolGamesxX** [MC-Minigames/TrapdoorSpleef#1]
We have error with plugin.

This server is running Spigot version git-Spigot-952179b-bc03b6f (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Here the error:

```
[01:37:58] [Server thread/WARN]: [MGTrapdoorSpleef] Task #564337 for MGTrapdoorSpleef v1.2.0 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R1/World
    at com.comze_instancelabs.trapdoorspleef.nms.VersionManager.getNMSHandler(VersionManager.java:7) ~[?:?]
    at com.comze_instancelabs.trapdoorspleef.nms.CraftMassBlockUpdate.<init>(CraftMassBlockUpdate.java:36) ~[?:?]
    at com.comze_instancelabs.trapdoorspleef.nms.CraftMassBlockUpdate.createMassBlockUpdater(CraftMassBlockUpdate.java:167) ~[?:?]
    at com.comze_instancelabs.trapdoorspleef.IArena.checkmbu(IArena.java:65) ~[?:?]
    at com.comze_instancelabs.trapdoorspleef.IArena.generateArena(IArena.java:30) ~[?:?]
    at com.comze_instancelabs.trapdoorspleef.IArena$1.run(IArena.java:57) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-952179b-bc03b6f]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-bc03b6f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R1.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-952179b-bc03b6f]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-952179b-bc03b6f]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
    ... 13 more
```

I was look in the code. I see the plugin do not support the 1.8 of spigot. Are you plan to update for the 1.8?

**Comment by mepeisen** [comment]
Hi.
There is a new project lead.
You find the new game with support up to 1.10 at https://github.com/MysticCity/TrapdoorSpleef
Please report issues at https://github.com/MysticCity/MinigamesAPI/issues

The current snapshot build is found at http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/Minigames-All-1.14.9-20160619.044520-15-bin.zip
Please help us with testing. Thanks
